---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.115.0
    releaseName: cluster-collector
    namespace: observability
    valuesInline:
      mode: deployment
      image:
        repository: otel/opentelemetry-collector-contrib
      replicaCount: 1
      presets:
        clusterMetrics:
          enabled: true
        kubernetesEvents:
          enabled: true
      config:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
          k8s_events:
        exporters:
          otlphttp/logs:
            endpoint: http://loki-write.observability.svc.cluster.local:3100/otlp
            tls:
              insecure: true
          otlphttp/metrics:
            endpoint: http://prometheus-server.observability.svc.cluster.local:9090/api/v1/otlp/v1/metrics
            tls:
              insecure: true
          otlp/traces:
            endpoint: tempo.observability.svc.cluster.local:4317
            tls:
              insecure: true
        service:
          pipelines:
            logs:
              receivers: [otlp, k8s_events]
              exporters: [otlphttp/logs]
            metrics:
              receivers: [otlp]
              exporters: [otlphttp/metrics]
            traces:
              receivers: [otlp]
              exporters: [otlp/traces]
      ports:
        prometheus:
          enabled: true
          containerPort: 9000
          servicePort: 9000
          hostPort: 9000
          protocol: TCP
