---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.115.0
    releaseName: cluster-collector
    namespace: observability
    valuesInline:
      mode: deployment
      image:
        repository: otel/opentelemetry-collector-k8s
      replicaCount: 1
      presets:
        clusterMetrics:
          enabled: true
        kubernetesEvents:
          enabled: true
      config:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
        exporters:
          otlphttp/logs:
            endpoint: http://loki-write.observability.svc.cluster.local:3100/otlp
            tls:
              insecure: true
            prometheus:
              endpoint: "0.0.0.0:9000"
              resource_to_telemetry_conversion:
                enabled: true
        service:
          pipelines:
            logs:
              receivers: [otlp]
              exporters: [otlphttp/logs]
            metrics:
              receivers: [otlp]
              exporters: [prometheus]
            traces:
              receivers: [otlp]
              exporters: [otlp]
