---
receivers:
  kubeletstats:
    collection_interval: 20s
    initial_delay: 1s
    auth_type: "serviceAccount"
    endpoint: "https://${env:K8S_NODE_NAME}:10250"
    insecure_skip_verify: true
    metric_groups:
      - node

processors:
  batch:

exporters:
  debug:

  otlp:
    endpoint: otelcol-gateway.observability.svc.cluster.local:4317
    tls:
      insecure: true

extensions:

service:
  pipelines:
    metrics:
      receivers:
        - kubeletstats
      processors:
        - batch
      exporters:
        - prometheus
