---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  labels:
    app: otelcol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
    spec:
      serviceAccountName: otelcol
      containers:
        - name: otelcol
          image: customcollectorimage
          imagePullPolicy: Always
          ports:
            - containerPort: 4317  # OTLP gRPC endpoint
            - containerPort: 55680  # OTLP HTTP endpoint
            - containerPort: 9000  # prometheus endpoint
          volumeMounts:
            - name: otelcol
              mountPath: /etc/otel/config.yaml
              subPath: config.yaml
          args:
            - "--config=/etc/otel/config.yaml"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: otelcol
          configMap:
            name: otelcol
      imagePullSecrets:
        - name: regcred
