---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.115.0
    releaseName: node-collector
    namespace: observability
    valuesInline:
      mode: daemonset
      image:
        repository: otel/opentelemetry-collector-k8s
      presets:
        kubernetesAttributes:
          enabled: true
        kubeletMetrics:
          enabled: true
        logsCollection:
          enabled: true
