---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.115.0
    releaseName: node-collector
    namespace: observability
    valuesInline:
      mode: daemonset
      image:
        repository: otel/opentelemetry-collector-k8s
      presets:
        kubernetesAttributes:
          enabled: true
        kubeletMetrics:
          enabled: true
        logsCollection:
          enabled: true
      config:
        exporters:
          otlp:
            endpoint: cluster-collector-opentelemetry-collector.observability.svc.cluster.local:4317
            tls:
              insecure: true
        service:
          pipelines:
            traces:
              exporters: [otlp]
            metrics:
              exporters: [otlp]
            logs:
              exporters: [otlp]
