apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-default-config
  labels:
    app: otel-default
data:
  config.yaml: |
    receivers:
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: events
            mode: watch
            group: events.k8s.io

      kubeletstats:
        collection_interval: 20s
        initial_delay: 1s
        auth_type: "tls"
        ca_file: "/path/to/ca.crt"
        key_file: "/path/to/apiserver.key"
        cert_file: "/path/to/apiserver.crt"
        endpoint: "https://192.168.64.1:10250"
        insecure_skip_verify: true

    processors:
      batch:

    exporters:
      otlphttp/logs:
        endpoint: http://loki-write.observability.svc.cluster.local:3100/otlp
        tls:
          insecure: true

    extensions:

    service:
      pipelines:
        logs:
          receivers:
          - k8sobjects
          processors:
          - batch
          exporters:
          - otlphttp/logs
        metrics:
          receivers:
          - kubeletstats
          processors:
          - batch
          exporters:
          - prometheus
