apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-default-config
  labels:
    app: otel-default
data:
  config.yaml: |
    receivers:
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: events
            mode: watch
            group: events.k8s.io

    processors:
      batch:

    exporters:
      otlphttp/logs:
        endpoint: http://loki-write.observability.svc.cluster.local:3100/otlp
        tls:
          insecure: true

    extensions:

    service:
      pipelines:
        logs:
          receivers:
          - k8sobjects
          processors:
          - batch
          exporters:
          - otlphttp/logs
