apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-default-config
  labels:
    app: otel-default
data:
  config.yaml: |
    receivers:
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: events
            mode: watch
            group: events.k8s.io

    processors:
      batch:

    exporters:
      otlphttp/logs:
        endpoint: http://loki-write.svc.cluster.local:3100/otlp
        tls:
          insecure: true

    extensions:
      healthcheckv2:
        use_v2: true
        http:
          endpoint: "0.0.0.0:8080"
          status:
            enabled: true
            path: "/health"
        grpc:
          endpoint: "0.0.0.0:13132"
          transport: "tcp"

    service:
      pipelines:
        logs:
          receivers:
          - k8sobjects
          processors:
          - batch
          exporters:
          - otlphttp/logs
      extensions:
      - healthcheckv2
