apiVersion: v1
kind: ServiceAccount
metadata:
   labels:
      app: otel-default
   name: otel-default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-default
  labels:
    app: otel-default
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "events.k8s.io"
  resources:
  - events
  verbs:
  - get
  - watch
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-default
  labels:
    app: otel-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-default
subjects:
- kind: ServiceAccount
  name: otel-default
  # Ideally the namespace would be come from the kustomization.
  # Something to look into later.
  namespace: observability
