---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  storage:
    size: 1Gi
    # Storage class needs to be defined here. Currently it can't be set at the operator level.
    storageClass: longhorn
