---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      # fsGroup: 5050

      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:14
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 22
              protocol: TCP
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"

          # envFrom:
          #   - secretRef:
          #       name: pgadmin-secrets

          volumeMounts:
            - mountPath: /data
              name: forgejo-pvc

          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"

      restartPolicy: Always

      volumes:
        - name: forgejo-pvc
          persistentVolumeClaim:
            claimName: forgejo-pvc
      #   - name: pgadmin-secrets
      #     secret:
      #       secretName: pgadmin-secrets