---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 22
              protocol: TCP
          envFrom:
            - configMapRef:
                name: forgejo-config
          env:
            - name: FORGEJO__database__USER
              valueFrom:
                secretKeyRef:
                  name: forgejo-postgres-app
                  key: username
            - name: FORGEJO__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: forgejo-postgres-app
                  key: password

          volumeMounts:
            - mountPath: /data
              name: forgejo-pvc

          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"

      restartPolicy: Always

      volumes:
        - name: forgejo-pvc
          persistentVolumeClaim:
            claimName: forgejo-pvc
