---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudflared
  - deployment.yaml
  - postgres-cluster.yaml
  - runner
  - service.yaml
  - volume.yaml

configMapGenerator:
  - name: forgejo-config
    envs:
      - config.env

images:
  - name: codeberg.org/forgejo/forgejo
    newTag: "14"
