---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-pgadmin
  namespace: pgadmin
spec:
  selector:
    matchLabels:
      app: cloudflared-pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared-pgadmin
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2025.1.0
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        # Each tunnel has an associated "credentials file" which authorizes machines
        # to run the tunnel. cloudflared will read this file from its local filesystem,
        # and it'll be stored in a k8s secret.
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: creds
        secret:
          secretName: pgadmin-tunnel-creds
      - name: config
        configMap:
          name: cloudflared-pgadmin
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-pgadmin
  namespace: pgadmin
data:
  config.yaml: |
    tunnel: pgadmin-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: pgadmin.giulia-harry.dev
      service: http://pgadmin:80
