{
 "title": "Node Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Leader",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\", node=\"leader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Follower 1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\", node=\"follower-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Follower 2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\", node=\"follower-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Follower 3",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\", node=\"follower-3\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}