---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

patches:
  - patch: |-
      - op: replace
        path: /roleRef/name
        value: otelcol-gateway
    target:
      kind: ClusterRoleBinding
      labelSelector: "app=otelcol-gateway"
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/configMap/name
        value: otelcol-gateway
    target:
      kind: Deployment
  - path: clusterrolebinding-patch.yaml
    target:
      kind: ClusterRoleBinding
  - path: clusterrole.patch.yaml
    target:
      kind: ClusterRole
  - path: volume.patch.yaml
    target:
      kind: Deployment
  - path: resources.patch.yaml
    target:
      kind: Deployment

configMapGenerator:
  - name: otelcol-gateway
    files:
      - config.yaml=otelcol-config.yaml

nameSuffix: -gateway

labels:
  - pairs:
      app: otelcol
    includeSelectors: true

images:
  - name: customcollectorimage
    newName: 'rg.fr-par.scw.cloud/otel-collector/debug:0.4.4'
