---
receivers:
  k8sobjects:
    auth_type: serviceAccount
    objects:
      - name: events
        mode: watch
        group: events.k8s.io

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

  prometheus:
    config:
      scrape_configs:
        - job_name: 'prometheus-node-exporter'
          scrape_interval: 5s
          static_configs:
            - targets:
              - 'prometheus-prometheus-node-exporter.svc.cluster.local:9100'

processors:
  batch:
  k8sattributes:
    auth_type: 'serviceAccount'

exporters:
  otlphttp/logs:
    endpoint: http://loki-write.observability.svc.cluster.local:3100/otlp
    tls:
      insecure: true

  debug:

  prometheus:
    endpoint: "0.0.0.0:9000"
    resource_to_telemetry_conversion:
      enabled: true

extensions:

service:
  pipelines:
    logs:
      receivers:
        - k8sobjects
      processors:
        - batch
        - k8sattributes
      exporters:
        - otlphttp/logs
        - debug
    metrics:
      receivers:
        - prometheus
        - otlp
      processors:
        - batch
        - k8sattributes
      exporters:
        - prometheus
