apiVersion: v1
kind: ServiceAccount
metadata:
   labels:
      app: otelcol-debug
   name: otelcol-debug

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol-debug
  labels:
    app: otelcol-debug
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  - nodes/stats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "events.k8s.io"
  resources:
  - events
  - nodes
  verbs:
  - get
  - watch
  - list
- nonResourceURLs:
  - "/metrics"
  - "/stats"
  verbs:
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol-debug
  labels:
    app: otelcol-debug
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otelcol-debug
subjects:
- kind: ServiceAccount
  name: otelcol-debug
  # Ideally the namespace would be come from the kustomization.
  # Something to look into later.
  namespace: observability
