tunnel: argocd-tunnel
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  - hostname: argocd.giulia-harry.dev
    service: https://argocd-server:443
    originRequest:
      noTLSVerify: true
  - service: http_status:404
