apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: rabbitmq-credentials
  namespace: default
data:
  valueFrom:
    secretKeyRef:
      name: rabbitmq-default-user
      namespace: rabbitmq