apiVersion: v1
kind: ServiceAccount
metadata:
   labels:
      app: otel-k8sreceiver
   name: otel-k8sreceiver

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-k8sreceiver
  labels:
    app: otel-k8sreceiver
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "events.k8s.io"
  resources:
  - events
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-k8sreceiver
  labels:
    app: otel-k8sreceiver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-k8sreceiver
subjects:
- kind: ServiceAccount
  name: otel-collector
  namespace: observability
