---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    path: resources/argocd
    repoURL: "https://git.giulia-harry.dev/harry/homelab"
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: "in-cluster"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
