---
kind: Namespace
apiVersion: v1
metadata:
  name: cert-manager

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: cert-manager
  sources:
    - repoURL: "https://charts.jetstack.io"
      chart: cert-manager
      targetRevision: 1.16.2
      helm:
        valuesObject:
          installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
