apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-tunnel
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
  sources:
  - repoURL: 'https://github.com/IrrelevantElephant/homelab'
    path: resources/cloudflare-tunnels
