---
kind: Namespace
apiVersion: v1
metadata:
  name: cnpg-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: "https://cloudnative-pg.github.io/charts"
      chart: cloudnative-pg
      targetRevision: 0.23.0
