---
kind: Namespace
apiVersion: v1
metadata:
  name: clustersecret

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustersecret
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: clustersecret
  sources:
    - repoURL: "https://charts.clustersecret.com/"
      chart: cluster-secret
      targetRevision: 0.4.5
