apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: default
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: jetstack/cert-manager
    targetRevision: v1.15.1
    helm:
      valuesObject:
        installCRDs: true
