---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: observability
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: grafana
      targetRevision: 9.4.5
      helm:
        valuesObject:
          persistence:
            enabled: true
            storageClassName: longhorn

          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Loki
                  type: loki
                  url: http://loki-read.observability.svc.cluster.local:3100
                  isDefault: true
                - name: Prometheus
                  type: prometheus
                  url: http://prometheus-server.observability.svc.cluster.local
                - name: kube-prometheus-stack-prometheus
                  type: prometheus
                  url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
                - name: Tempo
                  type: tempo
                  url: http://loki-read.observability.svc.cluster.local:3100
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
                - name: 'default'
                  orgId: 1
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default
          dashboards:
            default:
              node-exporter-full:
                gnetId: 1860
                revision: 37
                datasource: kube-prometheus-stack-prometheus

          # Required to prevent multi-attach volume error
          # https://github.com/elastisys/compliantkubernetes-apps/issues/185
          deploymentStrategy:
            type: Recreate

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
