---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: observability
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: grafana
      targetRevision: 7.3.3
      helm:
        valuesObject:
          persistence:
            enabled: true
            storageClassName: longhorn

          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Loki
                  type: loki
                  url: http://loki-read.observability.svc.cluster.local:3100
                  isDefault: true
                - name: Prometheus-otel
                  type: prometheus
                  url: http://prometheus-server.observability.svc.cluster.local
                - name: Prometheus-native
                  type: prometheus
                  url: http://prometheus-test-server.prometheus-test.svc.cluster.local
                - name: Tempo
                  type: tempo
                  url: http://loki-read.observability.svc.cluster.local:3100
          dashboards:
            default:
              node-exporter-full:
                gnetId: 1860
                revision: 37
                datasource: Prometheus-native

  syncPolicy:
    automated:
      prune: true
