kind: Namespace
apiVersion: v1
metadata:
  name: longhorn-system

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: longhorn-system
  sources:
  - repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: 1.7.2
    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        ingress:
          enabled: true
          ingressClassName: nginx
          host: longhorn.raspberrypi
          annotations:
            cert-manager.io/cluster-issuer: self-signed-issuer
            nginx.ingress.kubernetes.io/ssl-redirect: "true"

        longhornManager:
          log:
            format: json