---
kind: Namespace
apiVersion: v1
metadata:
  name: ingress-nginx

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: ingress-nginx
  sources:
    - repoURL: "https://kubernetes.github.io/ingress-nginx"
      chart: ingress-nginx
      targetRevision: 4.12.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
