---
kind: Namespace
apiVersion: v1
metadata:
  name: observability

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  source:
    path: resources/observability
    repoURL: "https://github.com/IrrelevantElephant/homelab"
    targetRevision: HEAD
    kustomize:
      namespace: observability
  destination:
    namespace: observability
    name: "in-cluster"
  syncPolicy:
    automated:
      prune: true
