---
kind: Namespace
apiVersion: v1
metadata:
  name: example-postgres

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-postgres
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: example-postgres
  sources:
    - repoURL: "https://github.com/IrrelevantElephant/homelab"
      path: resources/example-postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
