---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: observability
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: prometheus
      targetRevision: 25.15.0
      helm:
        valuesObject:
          serverFiles:
            prometheus.yml:
              scrape_configs:
                - job_name: prometheus
                  static_configs:
                    - targets:
                        - localhost:9090
                - job_name: otel
                  static_configs:
                    - targets:
                        - cluster-collector-opentelemetry-collector.observability.svc.cluster.local:9000

  syncPolicy:
    automated:
      prune: true
