---
kind: Namespace
apiVersion: v1
metadata:
  name: rabbitmq

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: rabbitmq
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: rabbitmq-cluster-operator
      targetRevision: 3.19.0
      helm:
        valuesObject:
          global:
            storageClass: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-clusters
  namespace: argocd
spec:
  project: default
  source:
    path: resources/rabbitmq
    repoURL: "https://github.com/IrrelevantElephant/homelab"
    targetRevision: HEAD
  destination:
    namespace: rabbitmq
    name: "in-cluster"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
