---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: tempo
      targetRevision: 1.7.2
