apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-nodereceiver-config
  labels:
    app: otelcol-nodereceiver
data:
  config.yaml: |
    receivers:
      kubeletstats:
        collection_interval: 20s
        initial_delay: 1s
        auth_type: "serviceAccount"
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
        metric_groups:
        - node

    processors:
      batch:

    exporters:
      debug:

      prometheus:
        endpoint: "0.0.0.0:9000"
        resource_to_telemetry_conversion:
          enabled: true

    extensions:

    service:
      pipelines:
        metrics:
          receivers:
          - kubeletstats
          processors:
          - batch
          exporters:
          - prometheus
