---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - cloudflared-deployment.yaml

configMapGenerator:
  - name: cloudflared-grafana
    files:
      - config.yaml=cloudflared-config.yaml
