name: Pipeline

on:
  push:
    branches: ["main"]

jobs:
  tag:
    name: "Tag repo"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: conventional_changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          preset: conventionalcommits
          github-token: ${{ secrets.github_token }}
          skip-commit: true
    outputs:
      version: ${{ steps.conventional_changelog.outputs.version }}

  argocd:
    name: "Get Argo Apps to sync"
    runs-on: ubuntu-24.04
    outputs:
      APPSTOSYNC: ${{ steps.list_apps.outputs.APPSTOSYNC }}
    steps:
      - name: "login"
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.12.4
          command: login
          options:  --grpc-web --password ${{ secrets.ARGOPASSWORD }} --username admin argocd.giulia-harry.dev
      - name: "list apps"
        id: list_apps
        shell: bash
        run: |
          APPSTOSYNC=$(argocd app list --grpc-web -o=json | jq '.[] | select(.status.sync.status != "Synced") | [.metadata.name]')
          echo $APPSTOSYNC | jq
          echo "APPSTOSYNC=$APPSTOSYNC" >> $GITHUB_OUTPUT
  
  sync-apps:
      name: "Sync Argo apps"
      runs-on: ubuntu-24.04
      needs: argocd
      strategy:
        matrix: ${{fromJson(needs.argocd.outputs.APPSTOSYNC)}}
      steps:
        - name: "login"
          uses: clowdhaus/argo-cd-action/@main
          with:
            version: 2.12.4
            command: login
            options:  --grpc-web --password ${{ secrets.ARGOPASSWORD }} --username admin argocd.giulia-harry.dev
        - name: "sync"
          shell: bash
          run: |
            echo ${{matrix}}
