name: Pipeline

on:
  push:
    branches: ["main"]

jobs:
  tag:
    name: "Tag repo"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: conventional_changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          preset: conventionalcommits
          github-token: ${{ secrets.github_token }}
          skip-commit: true
    outputs:
      version: ${{ steps.conventional_changelog.outputs.version }}

  argocd:
    name: "Sync ArgoCD"
    runs-on: ubuntu-24.04
    steps:
      - name: "Sync"
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.6.7
          command: version
          options: --client