apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-rabbitreceiver-config
  labels:
    app: otel-rabbitreceiver
data:
  config.yaml: |
    receivers:
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: events
            mode: watch
            group: events.k8s.io

    processors:
      batch:

    exporters:
      rabbitmq:
        connection:
          endpoint: amqp://rabbitmq.rabbitmq:5672
          auth:
            plain:
              username: ${env:RABBITMQ_USERNAME}
              password: ${env:RABBITMQ_PASSWORD}

    extensions:
      healthcheckv2:
        use_v2: true
        http:
          endpoint: "0.0.0.0:8080"
          status:
            enabled: true
            path: "/health"
        grpc:
          endpoint: "0.0.0.0:13132"
          transport: "tcp"

    service:
      pipelines:
        logs:
          receivers:
          - k8sobjects
          processors:
          - batch
          exporters:
          - rabbitmq
      extensions:
      - healthcheckv2
