apiVersion: v1
kind: ServiceAccount
metadata:
   labels:
      app: otel-rabbitreceiver
   name: otel-rabbitreceiver

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-rabbitreceiver
  labels:
    app: otel-rabbitreceiver
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "events.k8s.io"
  resources:
  - events
  verbs:
  - get
  - watch
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-rabbitreceiver
  labels:
    app: otel-rabbitreceiver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-rabbitreceiver
subjects:
- kind: ServiceAccount
  name: otel-collector
  # Ideally the namespace would be come from the kustomization.
  # Something to look into later.
  namespace: observability
